#!/bin/bash
clear
#--------------------------
# SSH_NET PRO
# CANAL TELEGRAM: @ssh
#--------------------------

# - Atualiza Lista/Pacotes/Sistema
dpkg --configure -a
apt update -y && apt upgrade -y
apt install unzip python3 -y

# - Execulta instalador
wget https://wget raw.githubusercontent.com/Rafaeloficiall/Rafaeloficial/main/Plus && chmod 777 Plus && ./Plus