#!/bin/bash
clear
#--------------------------
# SSH-PLUS
# CANAL TELEGRAM: @COMPANYOFICIAL
#--------------------------

# - Atualiza Lista/Pacotes/Sistema
dpkg --configure -a
apt update -y && apt upgrade -y
apt install unzip python3 -y

# - Execulta instalador
wget raw.githubusercontent.com/Rafaeloficiall/Rafaeloficial/main/script/${arch}/Plus && chmod 777 Plus && ./Plus
